#!/bin/bash
#Mover el puntero de serie
#El puntero permite saber por qué episodio nos llegamos.
#Moverlo es crucial para decirle al sistema cuál es el siguiente episodio que tenemos pendiente

function head.reset() {
	local idmedio="$1"

	db.executeUpdate "update episodio set esvisto = 0 where idmedio = $idmedio"
}

function head.markall() {
	local idmedio="$1"

	db.executeUpdate "update episodio set esvisto = 1 where idmedio = $idmedio"
}

function head.resetTemporada() {
	local idmedio="$1"
	local temporada="$2"

	db.executeUpdate "update episodio set esvisto = 0 where idmedio = $idmedio and temporada = $temporada"
}

function head.markTemporada() {
	local idmedio="$1"
	local temporada="$2"

	db.executeUpdate "update episodio set esvisto = 1 where idmedio = $idmedio and temporada = $temporada"
}

function head.forth() {
	local idmedio="$1"

	#echo "Idmedio: $idmedio" > /dev/tty
	local t=$(db.executeQuery "select min(temporada) from episodio where idmedio=$idmedio and esvisto=0")
	#echo "Temporada: $t" > /dev/tty
	local id=$(db.executeQuery "select min(id) from episodio where idmedio = $idmedio and temporada = $t and esvisto = 0")
	db.executeUpdate "update episodio set esvisto = 1 where id = $id"
}

function head.back() {
	local idmedio="$1"

	local t=$(db.executeQuery "select max(temporada) from episodio where idmedio=$idmedio and esvisto>0")
	local id=$(db.executeQuery "select max(id) from episodio where idmedio = $idmedio and temporada = $t and esvisto > 0")
	db.executeUpdate "update episodio set esvisto = 0 where id = $id"
}

function head.resetN() {
	local idmedio="$1"
	local n="$2"
	
	while [[ $n > 0 ]]; do
		head.back $idmedio
		(( n-- ))
	done
}

function head.markN() {
	local idmedio="$1"
	local n="$2"

	while [[ $n > 0 ]]; do
		head.forth $idmedio
		(( n-- ))
	done
}

function head.next() {
	local idmedio="$1"

	local t=$(db.executeQuery "select min(temporada) from episodio where idmedio=$idmedio and esvisto=0")

	if [[ "$t" == "" ]]; then
		echo "-1"
		exit
	fi
	
	local id=$(db.executeQuery "select min(id) from episodio where idmedio = $idmedio and temporada = $t and esvisto = 0")
	#echo "head.next Next: $id" > /dev/tty

	if [[ "$id" == "" ]]; then
		echo "-1"
	else
		echo "$id"
	fi
}