#!/bin/bash
#Módulo de ayuda de sintel

function help() {
	echo "sintel (Inteligencia sobre series) @Copyleft Julio Serrano 2017"
	echo
	echo "sintel -i | sintel -init"
	echo "	Inicializar la base de datos"
}


function help.info() {
    echo "help->help - Ayuda de sintel"
    echo
    echo -e "\tArgumentos: -"
    echo
    echo "La ayuda provista por esta función debería dar un listado extensivo"
    echo "de las opciones de sintel. Pero todavía está pendiente de escribirse."
    echo
    echo "Ejemplos:"
    echo -e "\tsintel -h"
}
