#!/bin/bash
# This file is part of Sintel.
#
# Sintel is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Sintel is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Sintel.  If not, see <https://www.gnu.org/licenses/>.
#
#
#Módulo de ayuda de sintel

function help() {
	echo "sintel versión $VERSION @Copyright GPL(3) Julio Serrano 2017 - 2019"
	echo "(Inteligencia sobre series)" 
	echo
	echo "Consulte la página del manual."
}


function help.info() {
    echo "help->help - Ayuda de sintel"
    echo
    echo -e "\tArgumentos: -"
    echo
    echo "La ayuda provista por esta función debería dar un listado extensivo"
    echo "de las opciones de sintel. Pero todavía está pendiente de escribirse."
    echo
    echo "Ejemplos:"
    echo -e "\tsintel -h"
}
