#!/bin/bash
# This file is part of Sintel.
#
# Sintel is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Sintel is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Sintel.  If not, see <https://www.gnu.org/licenses/>.
#
#
#Módulo de inicialización de la base de datos
#
#Tablas: medio, episodio, alternativo
#
#medio={id,nombre,fichero,torrent,streaming,esserie,esvisto}
#episodio={idmedio,temporada,episodio,fichero,torrent,streaming,esvisto}
#alternativo={idmedio,nombre}

init_SQL=$(cat << END
CREATE TABLE if not exists medio(
		id integer primary key,
		titulo varchar,
		fichero varchar,
		torrent integer,
		esserie integer,
		esvisto integer,
		esdescargado integer);
CREATE TABLE if not exists episodio (
		id integer primary key,
		idmedio integer,
		temporada integer,
		episodio integer,
		fichero varchar,
		torrent integer,
		esvisto integer,
		esdescargado integer,
		foreign key (idmedio) references medio(id));
CREATE TABLE if not exists alternativo (
		idmedio integer,
		nombre varchar,
		foreign key(idmedio) references medio(id));
CREATE TABLE if not exists ruta (
		ruta varchar primary key,
		reemplazo varchar);
CREATE TABLE if not exists anime (
		id integer primary key,
		titulo varchar,
		url varchar,
		alias varchar,
		episodio integer);
CREATE TABLE if not exists veronline (
		id integer primary key,
		titulo varchar,
		url varchar,
		etiquetas varchar,
		episodio integer);
END
)

# Creación de tablas nuevas
upd_SQL=$(cat << END
CREATE TABLE if not exists anime (
		id integer primary key,
		titulo varchar,
		url varchar,
		alias varchar,
		episodio integer);
CREATE TABLE if not exists veronline (
		id integer primary key,
		titulo varchar,
		url varchar,
		etiquetas varchar,
		episodio integer);
END
)

function init () {
	if [ -f "${global_DIR}/sintel.db" ]; then
		sqlite3 ${global_DIR}/sintel.db <<< "$upd_SQL"	
		# echo "La base de datos ya existe."
		exit
	fi
	echo "Inicializando la base de datos..."
	sqlite3 ${global_DIR}/sintel.db <<< "$init_SQL"
	echo "Base de datos inicializada."
}


function init.info() {
    echo "init->init - Inicializa la base de datos."
    echo
    echo -e "\tArgumentos: -"
    echo
    echo "La tarea de init es crear la base de datos si no existe"
    echo "y actualizarla con las nuevas tablas que vayan surgiendo."
    echo
    echo "El módulo init solo contiene la función init y algunas"
    echo "variables, por lo que no se ha incluído información propia"
    echo "del módulo en sí,"
    echo
    echo "Ejemplo:"
    echo -e "\tsintel -f init"
}
