#!/bin/bash
#Gestión de series
#
#Básicamente queremos utilizar la base de datos de momento como elemento adicional de dxtotal y mt o mtf y quizá 
#en el futuro, se use con exclusividad, sustituyendo al método de la carpeta de series.
#
#Se deben poder añadir series a seguir y episodios conforme se vayan descargando.
#Así mismo servirá para llevar la cuenta de los vistos en "ver".

declare -A SERIE
SERIE=( ["id"]=""  ["titulo"]="" ["fichero"]="" ["torrent"]="" ["esserie"]="" ["esvisto"]="" )
declare -A EPISODIO
EPISODIO=( ["id"]="" ["idmedio"]="" ["temporada"]="" ["episodio"]="" ["fichero"]="" ["torrent"]="" ["esvisto"]="" ["esdescargado"]="" )

function series.info() {
    echo "series - Gestión de series"
    echo
    echo "Este módulo es muy parecido a películas, aunque añade"
    echo "algunas funciones adicionales como aquellas que se"
    echo "cuidan de gestionar los episodios."
    echo
    echo "Registros: serie, episodio"
    echo
    echo "serie = id | titulo | fichero | torrent | esserie | esvisto"
    echo "episodio = id | idmedio | temporada | episodio | fichero |"
    echo "           torrent | esvisto | esdescargado"
}

function series.add() {
	local titulo="$1"

	$DEBUG && echo "> series.add" > /dev/tty
	db.executeUpdate "insert into medio (titulo, fichero, torrent, esserie, esvisto,esdescargado) values (\"$titulo\",\"\",-1,1,0,0)"	
	$DEBUG && echo "< series.add" > /dev/tty
	echo "$ROWID"
}

function series.add.info() {
    echo "series.add - "
    echo
    echo -e "\tArgumentos: "
    echo
    echo ""
    echo ""
    echo
    echo "Ejemplo:"
    echo -e "\t"
}

function series.getById() {
	local id="$1"

	$DEBUG && echo "> series.getById" > /dev/tty
	local res=$(db.executeQuery "select * from medio where id = $id and esserie=1")
	$DEBUG && echo "< series.getById" > /dev/tty
	echo "$res"
}

function series.getById.info() {
    echo "series.getById - "
    echo
    echo -e "\tArgumentos: "
    echo
    echo ""
    echo ""
    echo
    echo "Ejemplo:"
    echo -e "\t"
}

function series.getIdByTitulo() {
	local titulo="$1"

	$DEBUG && echo "> series.getByTitulo" > /dev/tty
	local res=$(db.executeQuery "select id from medio where esserie=1 and lower(titulo) = \"${titulo,,}\"")
	# if [[ $? != 0 ]]; then
	# 	echo "SQL: $sql"
	# fi
	$DEBUG && echo "< series.getByTitulo" > /dev/tty
	echo "$res"
}

function series.getIdByTitulo.info() {
    echo "series.getIdByTitulo - "
    echo
    echo -e "\tArgumentos: "
    echo
    echo ""
    echo ""
    echo
    echo "Ejemplo:"
    echo -e "\t"
}

function series.getByTitulo() {
	local titulo="$1"

	$DEBUG && echo "> series.getByTitulo" > /dev/tty
	local res=$(db.executeQuery "select * from medio where esserie=1 and titulo = \"$titulo\"")
	$DEBUG && echo "< series.getByTitulo" > /dev/tty
	echo "$res"
}

function series.getByTitulo.info() {
    echo "series.getByTitulo - "
    echo
    echo -e "\tArgumentos: "
    echo
    echo ""
    echo ""
    echo
    echo "Ejemplo:"
    echo -e "\t"
}

function series.getByFichero() {
	local fichero="$1"

	local res=$(db.executeQuery "select * from medio where esserie = 1 and fichero = \"$fichero\"")
	echo "$res"
}

function series.getByFichero.info() {
    echo "series.getByFichero - "
    echo
    echo -e "\tArgumentos: "
    echo
    echo ""
    echo ""
    echo
    echo "Ejemplo:"
    echo -e "\t"
}

function series.find() {
	local busqueda="$@"

	local res=$(db.executeQuery "select * from medio where esserie = 1 and titulo like \"%${busqueda}%\"")
	echo "$res"	
}

function series.find.info() {
    echo "series.find - "
    echo
    echo -e "\tArgumentos: "
    echo
    echo ""
    echo ""
    echo
    echo "Ejemplo:"
    echo -e "\t"
}

function series.getId() {
	local titulo="$1"

	local id=$(db.executeQuery "select id from medio where esserie = 1 and titulo = \"$titulo\"")
}

function series.getId.info() {
    echo "series.getId - "
    echo
    echo -e "\tArgumentos: "
    echo
    echo ""
    echo ""
    echo
    echo "Ejemplo:"
    echo -e "\t"
}

function series.remove() {
	local id="$1"

	db.executeUpdate "delete from medio where esserie = 1 and id = $id"
}

function series.remove.info() {
    echo "series.remove - "
    echo
    echo -e "\tArgumentos: "
    echo
    echo ""
    echo ""
    echo
    echo "Ejemplo:"
    echo -e "\t"
}

function series.updateFichero() {
	local id="$1"
	local fichero="$2"

	db.executeUpdate "update medio set fichero=\"$fichero\" where id = $id"
}

function series.updateFichero.info() {
    echo "series.updateFichero - "
    echo
    echo -e "\tArgumentos: "
    echo
    echo ""
    echo ""
    echo
    echo "Ejemplo:"
    echo -e "\t"
}

function series.updateTorrent() {
	local id="$1"
	local torrent="$2"

	db.executeUpdate "update medio set torrent=$torrent where id = $id"
}

function series.updateTorrent.info() {
    echo "series.updateTorrent - "
    echo
    echo -e "\tArgumentos: "
    echo
    echo ""
    echo ""
    echo
    echo "Ejemplo:"
    echo -e "\t"
}

function series.setVista() {
	local id="$1"

	db.executeUpdate "update medio set esvisto=1 where id = $id"
}

function series.setVista.info() {
    echo "series.setVista - "
    echo
    echo -e "\tArgumentos: "
    echo
    echo ""
    echo ""
    echo
    echo "Ejemplo:"
    echo -e "\t"
}

function series.setNoVista() {
	local id="$1"

	db.executeUpdate "update medio set esvisto=0 where id = $id"
}

function series.setNoVista.info() {
    echo "series.setNoVista - "
    echo
    echo -e "\tArgumentos: "
    echo
    echo ""
    echo ""
    echo
    echo "Ejemplo:"
    echo -e "\t"
}

function series.parse() {
	local datos="$1"

	$DEBUG && echo ">Entra en series.parse" > /dev/tty
	IFS='|' read -a datosa <<< "$datos"; IFS=" "
	SERIE[id]="${datosa[0]}"
	SERIE[titulo]="${datosa[1]}"
	SERIE[fichero]="${datosa[2]}"
	SERIE[torrent]="${datosa[3]}"
	SERIE[esserie]="${datosa[4]}"
	SERIE[esvisto]="${datosa[5]}"
	# SERIE[esdescargado]="${datosa[6]}"
	$DEBUG && echo "<Sale en series.parse" > /dev/tty
}

function series.parse.info() {
    echo "series.parse - "
    echo
    echo -e "\tArgumentos: "
    echo
    echo ""
    echo ""
    echo
    echo "Ejemplo:"
    echo -e "\t"
}

function series.parseToFile() {
	local datos="$1"

	series.parse "$datos"

	echo > /tmp/SERIE
	let i=0
	for key in ${!SERIE[@]}; do
		echo "$key ${SERIE[$key]}" >> /tmp/SERIE
	done
}

function series.parseToFile.info() {
    echo "series.parseToFile - "
    echo
    echo -e "\tArgumentos: "
    echo
    echo ""
    echo ""
    echo
    echo "Ejemplo:"
    echo -e "\t"
}

function series.getField() {
	local field="$1"

	let i=0
	for key in "${!SERIE[@]}"; do
		if [[ "$key" == "$field" ]]; then
			$DEBUG && echo "Coincide con $key. Salimos" > /dev/tty
			break
		fi
		(( i++ ))
	done
	$DEBUG && echo "El valor de i es $i" > /dev/tty
	if [[ $i < ${#SERIE[@]} ]]; then
		local res=$(grep "^$field" /tmp/SERIE | awk '{ print $2 };')
		echo "$res"
	else
		echo "-1"
	fi
}

function series.getField.info() {
    echo "series.getField - "
    echo
    echo -e "\tArgumentos: "
    echo
    echo ""
    echo ""
    echo
    echo "Ejemplo:"
    echo -e "\t"
}

function series.addEpisodio() {
	local idmedio="$1"
	local temporada="$2"
	local episodio="$3"
	local fichero="$4"
	local torrent="$5"

	db.executeUpdate "insert into episodio (idmedio, temporada, episodio, fichero, torrent, esvisto, esdescargado)\
	 values ($idmedio,$temporada,$episodio,\"$fichero\",$torrent,0,0)"
}

function series.addEpisodio.info() {
    echo "series.addEpisodio - "
    echo
    echo -e "\tArgumentos: "
    echo
    echo ""
    echo ""
    echo
    echo "Ejemplo:"
    echo -e "\t"
}

function series.getEpisodioById() {
	local id="$1"

	local res=$(db.executeQuery "select * from episodio where id = $id")
	echo "$res"
}

function series.getEpisodioById.info() {
    echo "series.getEpisodioById - "
    echo
    echo -e "\tArgumentos: "
    echo
    echo ""
    echo ""
    echo
    echo "Ejemplo:"
    echo -e "\t"
}

function series.getEpisodioByFichero() {
	local fichero="$1"

	local res=$(db.executeQuery "select * from episodio where fichero = \"$fichero\"")
	echo "$res"
}

function series.getEpisodioByFichero.info() {
    echo "series.getEpisodioByFichero - "
    echo
    echo -e "\tArgumentos: "
    echo
    echo ""
    echo ""
    echo
    echo "Ejemplo:"
    echo -e "\t"
}

function series.findEpisodio() {
	local busqueda="$@"

	local res=$(db.executeQuery "select * from episodio where fichero like \"%${busqueda}%\"")
	echo "$res"	
}

function series.findEpisodio.info() {
    echo "series.findEpisodio - "
    echo
    echo -e "\tArgumentos: "
    echo
    echo ""
    echo ""
    echo
    echo "Ejemplo:"
    echo -e "\t"
}

function series.getEpisodioId() {
	local idmedio="$1"
	local temporada="$2"
	local episodio="$3"

	local id=$(db.executeQuery "select id from episodio where idmedio = $idmedio and temporada = $temporada and episodio = $episodio")
	echo "$id"
}

function series.getEpisodioId.info() {
    echo "series.getEpisodioId - "
    echo
    echo -e "\tArgumentos: "
    echo
    echo ""
    echo ""
    echo
    echo "Ejemplo:"
    echo -e "\t"
}

function series.removeEpisodio() {
	local id="$1"

	db.executeUpdate "delete from episodio where id = $id"
}

function series.removeEpisodio.info() {
    echo "series.removeEpisodio - "
    echo
    echo -e "\tArgumentos: "
    echo
    echo ""
    echo ""
    echo
    echo "Ejemplo:"
    echo -e "\t"
}

function series.updateEpisodioFichero() {
	local id="$1"
	local fichero="$2"

	db.executeUpdate "update episodio set fichero=\"$fichero\" where id = $id"
}

function series.updateEpisodioFichero.info() {
    echo "series.updateEpisodioFichero - "
    echo
    echo -e "\tArgumentos: "
    echo
    echo ""
    echo ""
    echo
    echo "Ejemplo:"
    echo -e "\t"
}

function series.updateEpisodioTorrent() {
	local id="$1"
	local torrent="$2"

	db.executeUpdate "update episodio set torrent=$torrent where id = $id"
}

function series.updateEpisodioTorrent.info() {
    echo "series.updateEpisodioTorrent - "
    echo
    echo -e "\tArgumentos: "
    echo
    echo ""
    echo ""
    echo
    echo "Ejemplo:"
    echo -e "\t"
}

function series.setEpisodioVista() {
	local id="$1"

	db.executeUpdate "update episodio set esvisto=1 where id = $id"
}

function series.setEpisodioVista.info() {
    echo "series.setEpisodioVista - "
    echo
    echo -e "\tArgumentos: "
    echo
    echo ""
    echo ""
    echo
    echo "Ejemplo:"
    echo -e "\t"
}

function series.setEpisodioNoVista() {
	local id="$1"

	db.executeUpdate "update episodio set esvisto=0 where id = $id"
}

function series.setEpisodioNoVista.info() {
    echo "series.setEpisodioNoVista - "
    echo
    echo -e "\tArgumentos: "
    echo
    echo ""
    echo ""
    echo
    echo "Ejemplo:"
    echo -e "\t"
}

function series.setEpisodioDescargado() {
	local id="$1"

	db.executeUpdate "update episodio set esdescargado=1 where id = $id"
}

function series.setEpisodioDescargado.info() {
    echo "series.setEpisodioDescargado - "
    echo
    echo -e "\tArgumentos: "
    echo
    echo ""
    echo ""
    echo
    echo "Ejemplo:"
    echo -e "\t"
}

function series.setEpisodioNoDescargado() {
	local id="$1"

	db.executeUpdate "update episodio set esdescargado=0 where id = $id"
}

function series.setEpisodioNoDescargado.info() {
    echo "series.setEpisodioNoDescargado - "
    echo
    echo -e "\tArgumentos: "
    echo
    echo ""
    echo ""
    echo
    echo "Ejemplo:"
    echo -e "\t"
}

function series.parseEpisodio() {
	local datos="$1"

	IFS='|' read -a datosa <<< "$datos"; IFS=" "

	EPISODIO[id]="${datosa[0]}"
	EPISODIO[idmedio]=${datosa[1]}
	EPISODIO[temporada]="${datosa[2]}"
	EPISODIO[episodio]="${datosa[3]}"
	EPISODIO[fichero]="${datosa[4]}"
	EPISODIO[torrent]="${datosa[5]}"
	EPISODIO[esvisto]="${datosa[6]}"
	EPISODIO[esdescargado]="${datosa[7]}"
}

function series.parseEpisodio.info() {
    echo "series.parseEpisodio - "
    echo
    echo -e "\tArgumentos: "
    echo
    echo ""
    echo ""
    echo
    echo "Ejemplo:"
    echo -e "\t"
}

function series.parseEpisodioToFile() {
	local datos="$1"

	series.parseEpisodio "$datos"

	echo > /tmp/EPISODIO
	let i=0
	for key in ${!EPISODIO[@]}; do
		echo "$key ${EPISODIO[$key]}" >> /tmp/EPISODIO
	done
}

function series.parseEpisodioToFile.info() {
    echo "series.parseEpisodioToFile - "
    echo
    echo -e "\tArgumentos: "
    echo
    echo ""
    echo ""
    echo
    echo "Ejemplo:"
    echo -e "\t"
}

function series.getEpisodioField() {
	local field="$1"

	let i=0
	for key in "${!EPISODIO[@]}"; do
		if [[ "$key" == "$field" ]]; then
			$DEBUG && echo "Coincide con $key. Salimos" > /dev/tty
			break
		fi
		(( i++ ))
	done
	$DEBUG && echo "El valor de i es $i" > /dev/tty
	if [[ $i < ${#EPISODIO[@]} ]]; then
		local res=$(grep "^$field " /tmp/EPISODIO | awk '{ print $2 };')
		echo "$res"
	else
		echo "-1"
	fi
}

function series.getEpisodioField.info() {
    echo "series.getEpisodioField - "
    echo
    echo -e "\tArgumentos: "
    echo
    echo ""
    echo ""
    echo
    echo "Ejemplo:"
    echo -e "\t"
}

function series.parseTemporada() {
	local te="$1"

	IFS='x' read -a aux <<< "$te"; IFS=" "
	echo "${aux[0]}"
}

function series.parseTemporada.info() {
    echo "series.parseTemporada - "
    echo
    echo -e "\tArgumentos: "
    echo
    echo ""
    echo ""
    echo
    echo "Ejemplo:"
    echo -e "\t"
}

function series.parseEpisodioNum() {
	local te="$1"

	IFS='x' read -a aux <<< "$te"; IFS=" "
	echo "${aux[1]}"
}

function series.parseEpisodioNum.info() {
    echo "series.parseEpisodioNum - "
    echo
    echo -e "\tArgumentos: "
    echo
    echo ""
    echo ""
    echo
    echo "Ejemplo:"
    echo -e "\t"
}

function series.screenEpisodio() {
	echo "${EPISODIO[id]} ${EPISODIO[idmedio]} ${EPISODIO[temporada]} ${EPISODIO[episodio]}" > /dev/tty
	# ${EPISODIO[fichero]}
	# ${EPISODIO[torrent]}
	# ${EPISODIO[esvisto]}
	# ${EPISODIO[esdescargado]}
}

function series.screenEpisodio.info() {
    echo "series.screenEpisodio - "
    echo
    echo -e "\tArgumentos: "
    echo
    echo ""
    echo ""
    echo
    echo "Ejemplo:"
    echo -e "\t"
}
