#!/bin/bash
#Comunicación con Transmission para obtener información de torrents

torrents_SERVER="192.168.0.64:9091 --auth admin:admin"

function torrents.lastId(){
	local preid=$(transmission-remote $torrents_SERVER -l | tac | grep -Em 1 '^ [0-9]{1,5}' | awk '{print $1}')
	echo "Preid: $preid" > /dev/tty
	local id=$(trim "$preid")
	echo "Id: $id" > /dev/tty
	echo "$id"
}

function torrents.info() {
	local id="$1"

	local res=$(transmission-remote $torrents_SERVER -t $id -i)
	echo "$res" > /tmp/TORRENT_INFO
	echo "$res"
}

function torrents.parse() {
	local field="$1"

	local res=`grep "$field:" < /tmp/TORRENT_INFO`
	res="${res##*: }"
	echo "$res"
}

function torrents.isDone() {
	local id="$1"

	local res=$(transmission-remote $torrents_SERVER -t $id -i | grep "Hash:")
	res="${res##*: }"
	echo "$res"
}

function torrents.getName() {
	local id="$1"

	local res=$(transmission-remote $torrents_SERVER -t $id -i | grep "Name:")
	res="${res##*: }"
	echo "$res"
}

function torrents.getLocation() {
	local id="$1"

	local res=$(transmission-remote $torrents_SERVER -t $id -i | grep "Location:")
	res="${res##*: }"
	echo "$res"
}